### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by stephanos** [FormidableLabs/webpack-stats-plugin#2]
When I add
```
new StatsWriterPlugin({})
```
to my plugins, this happens:

```
Message:
    undefined is not a function
Details:
    domain: [object Object]
    domainThrown: true
```

PS: running on node 0.12
